# Generated by Django 5.2.1 on 2025-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_parsed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
