# Generated by Django 5.2.1 on 2025-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0002_category_last_parsed_category_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
