# Generated by Django 5.2.1 on 2025-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0006_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
