# Generated by Django 5.2.1 on 2025-05-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0007_alter_product_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
