# Generated by Django 5.2.1 on 2025-05-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0009_product_product_id_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
