# Generated by Django 5.2.1 on 2025-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0010_category_category_id_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
