# Generated by Django 5.2.1 on 2025-05-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0011_alter_category_category_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
