# Generated by Django 5.2.1 on 2025-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0012_category_is_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parse_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
