# Generated by Django 5.2.1 on 2025-05-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0013_product_parse_detail_alter_product_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
