# Generated by Django 5.2.1 on 2025-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0014_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='RUB', max_length=10),
        ),
    ]
