# Generated by Django 5.2.1 on 2025-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0015_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
