# Generated by Django 5.2.1 on 2025-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0016_product_is_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_related_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
