# Generated by Django 5.2.1 on 2025-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0017_product_is_related_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='html_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
