# Generated by Django 5.2.1 on 2025-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0019_reviewphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_update',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
