# Generated by Django 5.2.1 on 2025-06-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0020_remove_product_last_update_product_characteristic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='html_page',
        ),
        migrations.CreateModel(
            name='ProductHTMLPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_pages', to='yandex_market.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
