# Generated by Django 5.2.1 on 2025-06-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0021_alter_product_brand_remove_characteristic_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductHTMLPage',
        ),
    ]
