# Generated by Django 5.2.1 on 2025-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0022_delete_producthtmlpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
