# Generated by Django 5.2.1 on 2025-06-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0023_alter_product_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
