# Generated by Django 5.2.1 on 2025-06-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0024_alter_product_rating_alter_product_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
