# Generated by Django 5.2.1 on 2025-06-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0025_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
