# Generated by Django 5.2.1 on 2025-06-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0026_productimage_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
