# Generated by Django 5.2.1 on 2025-06-04 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0028_alter_review_comment_alter_review_cons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='yandex_market.review'),
        ),
    ]
