# Generated by Django 5.2.1 on 2025-06-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0029_alter_product_name_alter_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
