# Generated by Django 5.2.1 on 2025-06-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0030_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updatet_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
