# Generated by Django 5.2.1 on 2025-06-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0031_review_created_at_review_updatet_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='updatet_at',
            new_name='updated_at',
        ),
    ]
