# Generated by Django 5.2.1 on 2025-06-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0032_rename_updatet_at_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
