# Generated by Django 5.2.1 on 2025-06-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0033_alter_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
