# Generated by Django 5.2.1 on 2025-06-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0035_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('dprice', 'Discount Price'), ('aprice', 'Actual Price'), ('rating', 'Rating'), ('', 'Default')], default='', max_length=10),
        ),
    ]
