# Generated by Django 5.2.1 on 2025-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0036_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
