# Generated by Django 5.2.1 on 2025-06-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0037_category_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=101, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='yandex_market.category'),
        ),
    ]
