# Generated by Django 5.2.1 on 2025-06-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0038_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
