# Generated by Django 5.2.1 on 2025-06-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0039_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_parsed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_related_parsed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='parse_detail',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
