# Generated by Django 5.2.1 on 2025-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(default=None, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
