# Generated by Django 5.2.1 on 2025-05-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0003_remove_product_image_url_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(default=None, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
