# Generated by Django 5.2.1 on 2025-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0004_product_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
