# Generated by Django 5.2.1 on 2025-05-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0005_alter_product_brand_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_category',
        ),
    ]
