# Generated by Django 5.2.1 on 2025-05-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0006_rename_parent_category_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='url_category',
        ),
    ]
