# Generated by Django 5.2.1 on 2025-05-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0007_rename_url_category_url_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
    ]
