# Generated by Django 5.2.1 on 2025-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0008_alter_product_brand_alter_product_product_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_parsed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
