# Generated by Django 5.2.1 on 2025-05-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0009_category_last_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
