# Generated by Django 5.2.1 on 2025-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0010_product_is_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url_category',
            field=models.URLField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(db_index=True, max_length=5000, unique=True),
        ),
    ]
