# Generated by Django 5.2.1 on 2025-05-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('last_access_date', models.DateField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('business', models.BooleanField(default=False)),
                ('offer_total_count', models.IntegerField(default=0)),
                ('offer_active_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='birbir.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('full_address', models.CharField(blank=True, max_length=500, null=True)),
                ('published_at', models.BigIntegerField()),
                ('url', models.URLField(max_length=500)),
                ('business', models.BooleanField(default=False)),
                ('courier_delivery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='birbir.category')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.BigIntegerField(unique=True)),
                ('uuid', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('crop_url_template', models.URLField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='birbir.product')),
            ],
        ),
    ]
