# Generated by Django 5.2.1 on 2025-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
