# Generated by Django 5.2.1 on 2025-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0002_category_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='parsed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
