# Generated by Django 5.2.1 on 2025-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0005_product_developer_product_status_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
