# Generated by Django 5.2.1 on 2025-05-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0007_alter_product_full_address_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
