# Generated by Django 5.2.1 on 2025-05-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0009_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
