# Generated by Django 5.2.1 on 2025-05-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0011_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
