# Generated by Django 5.2.1 on 2025-05-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0012_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='SiteToken',
        ),
    ]
