# Generated by Django 5.2.1 on 2025-05-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0013_rename_token_sitetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetoken',
            name='token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
