# Generated by Django 5.2.1 on 2025-05-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0014_alter_sitetoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
