# Generated by Django 5.2.1 on 2025-05-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbir', '0015_category_is_processing_category_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
